//
// UntitledView.h
// Generated by Core Animator version 1.0.3 on 15/4/24.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface UntitledView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// down
- (void)addDownAnimation;
- (void)addDownAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addDownAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addDownAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addDownAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeDownAnimation;

// up
- (void)addUpAnimation;
- (void)addUpAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addUpAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addUpAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addUpAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeUpAnimation;

- (void)removeAllAnimations;

@end