# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'
pod 'SDWebImage', '~> 3.7.2'
pod 'AFNetworking', '~> 2.5.3'
target 'WebSdkDome' do

end

target 'WebSdkDomeTests' do

end
